In [3]:
#IMPORTING THE REQUIRED LIBRARIES
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [4]:
#IMPORTING THE DATASET
ds1 = pd.read_csv('https://raw.githubusercontent.com/dsrscientist/dataset4/main/Grades.csv')
ds1

,Seat No.,PH-121,HS-101,CY-105,HS-105/12,MT-111,CS-105,CS-106,EL-102,EE-119,...,CS-312,CS-317,CS-403,CS-421,CS-406,CS-414,CS-419,CS-423,CS-412,CGPA
0,CS-97001,B-,D+,C-,C,C-,D+,D,C-,B-,...,C-,C-,C-,C-,A-,A,C-,B,A-,2.205
1,CS-97002,A,D,D+,D,B-,C,D,A,D+,...,D+,D,C,D,A-,B-,C,C,B,2.008
2,CS-97003,A,B,A,B-,B+,A,B-,B+,A-,...,B,B,A,C,A,A,A,A-,A,3.608
3,CS-97004,D,C+,D+,D,D,A-,D+,C-,D,...,D+,C,D+,C-,B-,B,C+,C+,C+,1.906
4,CS-97005,A-,A-,A-,B+,A,A,A-,B+,A,...,B-,B+,B+,B-,A-,A,A-,A-,A,3.448
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,CS-97567,B,A,A,A-,A+,A,A-,A-,A+,...,A-,A-,A,A,A,B+,B+,B,A,3.798
567,CS-97568,A+,A,A,A,A,A,A,A-,A,...,B+,B+,A,A,A-,B,A-,C,A-,3.772
568,CS-97569,B,A,A-,B+,A,A,A,A,A,...,A-,B,A,B+,A,C,B+,A-,A-,3.470
569,CS-97570,A,B+,D,A,D,D+,B-,C-,B-,...,D,B,B,C-,D,C,B,B-,C,2.193
570,CS-97571,C,D,D,C,C,D+,B,C+,C,...,C+,C,B-,D,F,C-,B+,D,C-,1.753

In [5]:
ds1.shape

(571, 43)

In [6]:
#CHECHING FOR THE DATA TYPES OF EACH COLUMN
ds1.dtypes

Seat No.      object
PH-121        object
HS-101        object
CY-105        object
HS-105/12     object
MT-111        object
CS-105        object
CS-106        object
EL-102        object
EE-119        object
ME-107        object
CS-107        object
HS-205/20     object
MT-222        object
EE-222        object
MT-224        object
CS-210        object
CS-211        object
CS-203        object
CS-214        object
EE-217        object
CS-212        object
CS-215        object
MT-331        object
EF-303        object
HS-304        object
CS-301        object
CS-302        object
TC-383        object
MT-442        object
EL-332        object
CS-318        object
CS-306        object
CS-312        object
CS-317        object
CS-403        object
CS-421        object
CS-406        object
CS-414        object
CS-419        object
CS-423        object
CS-412        object
CGPA         float64
dtype: object

In [7]:
#CHECKING FOR NULL VALUES
ds1.isnull().sum()

Seat No.      0
PH-121        0
HS-101        0
CY-105        1
HS-105/12     1
MT-111        2
CS-105        0
CS-106        2
EL-102        2
EE-119        2
ME-107        2
CS-107        2
HS-205/20     5
MT-222        5
EE-222        7
MT-224        7
CS-210        7
CS-211        5
CS-203        5
CS-214        6
EE-217        6
CS-212        6
CS-215        6
MT-331        9
EF-303       10
HS-304       10
CS-301       10
CS-302       10
TC-383       10
MT-442       10
EL-332        9
CS-318        9
CS-306        9
CS-312       10
CS-317       12
CS-403       12
CS-421       12
CS-406       85
CS-414       13
CS-419       13
CS-423       14
CS-412       79
CGPA          0
dtype: int64

In [8]:
ds1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 571 entries, 0 to 570
Data columns (total 43 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Seat No.   571 non-null    object
 1   PH-121     571 non-null    object
 2   HS-101     571 non-null    object
 3   CY-105     570 non-null    object
 4   HS-105/12  570 non-null    object
 5   MT-111     569 non-null    object
 6   CS-105     571 non-null    object
 7   CS-106     569 non-null    object
 8   EL-102     569 non-null    object
 9   EE-119     569 non-null    object
 10  ME-107     569 non-null    object
 11  CS-107     569 non-null    object
 12  HS-205/20  566 non-null    object
 13  MT-222     566 non-null    object
 14  EE-222     564 non-null    object
 15  MT-224     564 non-null    object
 16  CS-210     564 non-null    object
 17  CS-211     566 non-null    object
 18  CS-203     566 non-null    object
 19  CS-214     565 non-null    object
 20  EE-217     565 non-null    object
 21  CS-212     565 non-null    object
 22  CS-215     565 non-null    object
 23  MT-331     562 non-null    object
 24  EF-303     561 non-null    object
 25  HS-304     561 non-null    object
 26  CS-301     561 non-null    object
 27  CS-302     561 non-null    object
 28  TC-383     561 non-null    object
 29  MT-442     561 non-null    object
 30  EL-332     562 non-null    object
 31  CS-318     562 non-null    object
 32  CS-306     562 non-null    object
 33  CS-312     561 non-null    object
 34  CS-317     559 non-null    object
 35  CS-403     559 non-null    object
 36  CS-421     559 non-null    object
 37  CS-406     486 non-null    object
 38  CS-414     558 non-null    object
 39  CS-419     558 non-null    object
 40  CS-423     557 non-null    object
 41  CS-412     492 non-null    object
 42  CGPA       571 non-null    float64
dtypes: float64(1), object(42)
memory usage: 191.9+ KB

In [9]:
#SETTING "COUNTRY" COLUMN AS THE INDEX OF THE DATASET
ds1.set_index('Seat No.',inplace=True)
ds1

,PH-121,HS-101,CY-105,HS-105/12,MT-111,CS-105,CS-106,EL-102,EE-119,ME-107,...,CS-312,CS-317,CS-403,CS-421,CS-406,CS-414,CS-419,CS-423,CS-412,CGPA
Seat No.,,,,,,,,,,,,,,,,,,,,,
CS-97001,B-,D+,C-,C,C-,D+,D,C-,B-,C-,...,C-,C-,C-,C-,A-,A,C-,B,A-,2.205
CS-97002,A,D,D+,D,B-,C,D,A,D+,D,...,D+,D,C,D,A-,B-,C,C,B,2.008
CS-97003,A,B,A,B-,B+,A,B-,B+,A-,A-,...,B,B,A,C,A,A,A,A-,A,3.608
CS-97004,D,C+,D+,D,D,A-,D+,C-,D,C+,...,D+,C,D+,C-,B-,B,C+,C+,C+,1.906
CS-97005,A-,A-,A-,B+,A,A,A-,B+,A,A-,...,B-,B+,B+,B-,A-,A,A-,A-,A,3.448
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CS-97567,B,A,A,A-,A+,A,A-,A-,A+,B+,...,A-,A-,A,A,A,B+,B+,B,A,3.798
CS-97568,A+,A,A,A,A,A,A,A-,A,A,...,B+,B+,A,A,A-,B,A-,C,A-,3.772
CS-97569,B,A,A-,B+,A,A,A,A,A,B,...,A-,B,A,B+,A,C,B+,A-,A-,3.470
CS-97570,A,B+,D,A,D,D+,B-,C-,B-,C-,...,D,B,B,C-,D,C,B,B-,C,2.193
CS-97571,C,D,D,C,C,D+,B,C+,C,D+,...,C+,C,B-,D,F,C-,B+,D,C-,1.753

In [10]:
mode = ds1.filter(['CY-105','HS-105/12','MT-111','CS-106','EL-102','EE-119','ME-107','CS-107','HS-205/20','MT-222','EE-222','MT-224','CS-210','CS-211','CS-203','CS-214','EE-217','CS-212','CS-215','MT-331','EF-303','HS-304','CS-301','CS-302','TC-383','MT-442','EL-332','CS-318','CS-306','CS-312','CS-317','CS-403','CS-421','CS-406','CS-414','CS-419','CS-423','CS-412']).mode()
print(mode)

  CY-105 HS-105/12 MT-111 CS-106 EL-102 EE-119 ME-107 CS-107 HS-205/20 MT-222  \
0      A         A     A-     A-     A-     A-     A-      A        A-     A-

   ... CS-306 CS-312 CS-317 CS-403 CS-421 CS-406 CS-414 CS-419 CS-423 CS-412
0  ...     A-     A+     B-      A      B     A-      A     A-     A-     A-

[1 rows x 38 columns]

In [11]:
cols = ['CY-105','HS-105/12','MT-111','CS-106','EL-102','EE-119','ME-107','CS-107','HS-205/20','MT-222','EE-222','MT-224','CS-210','CS-211','CS-203','CS-214','EE-217','CS-212','CS-215','MT-331','EF-303','HS-304','CS-301','CS-302','TC-383','MT-442','EL-332','CS-318','CS-306','CS-312','CS-317','CS-403','CS-421','CS-406','CS-414','CS-419','CS-423','CS-412']
ds1[cols]=ds1[cols].fillna(ds1.mode().iloc[0])
ds1

,PH-121,HS-101,CY-105,HS-105/12,MT-111,CS-105,CS-106,EL-102,EE-119,ME-107,...,CS-312,CS-317,CS-403,CS-421,CS-406,CS-414,CS-419,CS-423,CS-412,CGPA
Seat No.,,,,,,,,,,,,,,,,,,,,,
CS-97001,B-,D+,C-,C,C-,D+,D,C-,B-,C-,...,C-,C-,C-,C-,A-,A,C-,B,A-,2.205
CS-97002,A,D,D+,D,B-,C,D,A,D+,D,...,D+,D,C,D,A-,B-,C,C,B,2.008
CS-97003,A,B,A,B-,B+,A,B-,B+,A-,A-,...,B,B,A,C,A,A,A,A-,A,3.608
CS-97004,D,C+,D+,D,D,A-,D+,C-,D,C+,...,D+,C,D+,C-,B-,B,C+,C+,C+,1.906
CS-97005,A-,A-,A-,B+,A,A,A-,B+,A,A-,...,B-,B+,B+,B-,A-,A,A-,A-,A,3.448
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CS-97567,B,A,A,A-,A+,A,A-,A-,A+,B+,...,A-,A-,A,A,A,B+,B+,B,A,3.798
CS-97568,A+,A,A,A,A,A,A,A-,A,A,...,B+,B+,A,A,A-,B,A-,C,A-,3.772
CS-97569,B,A,A-,B+,A,A,A,A,A,B,...,A-,B,A,B+,A,C,B+,A-,A-,3.470
CS-97570,A,B+,D,A,D,D+,B-,C-,B-,C-,...,D,B,B,C-,D,C,B,B-,C,2.193
CS-97571,C,D,D,C,C,D+,B,C+,C,D+,...,C+,C,B-,D,F,C-,B+,D,C-,1.753

In [12]:
#CHECKING FOR NULL VALUES
ds1.isnull().sum()

PH-121       0
HS-101       0
CY-105       0
HS-105/12    0
MT-111       0
CS-105       0
CS-106       0
EL-102       0
EE-119       0
ME-107       0
CS-107       0
HS-205/20    0
MT-222       0
EE-222       0
MT-224       0
CS-210       0
CS-211       0
CS-203       0
CS-214       0
EE-217       0
CS-212       0
CS-215       0
MT-331       0
EF-303       0
HS-304       0
CS-301       0
CS-302       0
TC-383       0
MT-442       0
EL-332       0
CS-318       0
CS-306       0
CS-312       0
CS-317       0
CS-403       0
CS-421       0
CS-406       0
CS-414       0
CS-419       0
CS-423       0
CS-412       0
CGPA         0
dtype: int64

In [13]:
#SEPERATING CATEGORICAL AND NUMERICAL COLUMNS
cat_col=[]
num_col=[]
for i in ds1.dtypes.index:
    if ds1.dtypes[i]=="object":
        cat_col.append(i)
    else:
        num_col.append(i)
print(cat_col)
print(num_col)

['PH-121', 'HS-101', 'CY-105', 'HS-105/12', 'MT-111', 'CS-105', 'CS-106', 'EL-102', 'EE-119', 'ME-107', 'CS-107', 'HS-205/20', 'MT-222', 'EE-222', 'MT-224', 'CS-210', 'CS-211', 'CS-203', 'CS-214', 'EE-217', 'CS-212', 'CS-215', 'MT-331', 'EF-303', 'HS-304', 'CS-301', 'CS-302', 'TC-383', 'MT-442', 'EL-332', 'CS-318', 'CS-306', 'CS-312', 'CS-317', 'CS-403', 'CS-421', 'CS-406', 'CS-414', 'CS-419', 'CS-423', 'CS-412']
['CGPA']

In [14]:
# LABEL ENCODING TECHNIQUE
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in cat_col:
    ds1[i]=le.fit_transform(ds1[i].astype(str))
ds1

,PH-121,HS-101,CY-105,HS-105/12,MT-111,CS-105,CS-106,EL-102,EE-119,ME-107,...,CS-312,CS-317,CS-403,CS-421,CS-406,CS-414,CS-419,CS-423,CS-412,CGPA
Seat No.,,,,,,,,,,,,,,,,,,,,,
CS-97001,5,10,8,6,8,10,9,8,5,8,...,8,8,8,8,2,0,8,3,2,2.205
CS-97002,0,9,10,9,5,6,9,0,10,9,...,10,9,6,9,2,5,6,6,3,2.008
CS-97003,0,3,0,5,4,0,5,4,2,2,...,3,3,0,6,0,0,0,2,0,3.608
CS-97004,9,7,10,9,9,2,10,8,9,7,...,10,6,10,8,5,3,7,7,7,1.906
CS-97005,2,2,2,4,0,0,2,4,0,2,...,5,4,4,5,2,0,2,2,0,3.448
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CS-97567,3,0,0,2,1,0,2,2,1,4,...,2,2,0,0,0,4,4,3,0,3.798
CS-97568,1,0,0,0,0,0,0,2,0,0,...,4,4,0,0,2,3,2,6,2,3.772
CS-97569,3,0,2,4,0,0,0,0,0,3,...,2,3,0,4,0,6,4,2,2,3.470
CS-97570,0,4,9,0,9,10,5,8,5,8,...,9,3,3,8,9,6,3,5,6,2.193
CS-97571,6,9,9,6,6,10,3,7,6,10,...,7,6,5,9,11,8,4,9,8,1.753

In [15]:
#SEPERATING INDEPENDENT VARIABLES AND TARGET
x1 = ds1.drop('CGPA',axis=1)
y1 = ds1['CGPA']
print(x1)

          PH-121  HS-101  CY-105  HS-105/12  MT-111  CS-105  CS-106  EL-102  \
Seat No.
CS-97001       5      10       8          6       8      10       9       8
CS-97002       0       9      10          9       5       6       9       0
CS-97003       0       3       0          5       4       0       5       4
CS-97004       9       7      10          9       9       2      10       8
CS-97005       2       2       2          4       0       0       2       4
...          ...     ...     ...        ...     ...     ...     ...     ...
CS-97567       3       0       0          2       1       0       2       2
CS-97568       1       0       0          0       0       0       0       2
CS-97569       3       0       2          4       0       0       0       0
CS-97570       0       4       9          0       9      10       5       8
CS-97571       6       9       9          6       6      10       3       7

          EE-119  ME-107  ...  CS-306  CS-312  CS-317  CS-403  CS-421  CS-406  \
Seat No.                  ...
CS-97001       5       8  ...       6       8       8       8       8       2
CS-97002      10       9  ...       9      10       9       6       9       2
CS-97003       2       2  ...       2       3       3       0       6       0
CS-97004       9       7  ...       8      10       6      10       8       5
CS-97005       0       2  ...       2       5       4       4       5       2
...          ...     ...  ...     ...     ...     ...     ...     ...     ...
CS-97567       1       4  ...       4       2       2       0       0       0
CS-97568       0       0  ...       2       4       4       0       0       2
CS-97569       0       3  ...       4       2       3       0       4       0
CS-97570       5       8  ...       4       9       3       3       8       9
CS-97571       6      10  ...      10       7       6       5       9      11

          CS-414  CS-419  CS-423  CS-412
Seat No.
CS-97001       0       8       3       2
CS-97002       5       6       6       3
CS-97003       0       0       2       0
CS-97004       3       7       7       7
CS-97005       0       2       2       0
...          ...     ...     ...     ...
CS-97567       4       4       3       0
CS-97568       3       2       6       2
CS-97569       6       4       2       2
CS-97570       6       3       5       6
CS-97571       8       4       9       8

[571 rows x 41 columns]

In [16]:
y1

Seat No.
CS-97001    2.205
CS-97002    2.008
CS-97003    3.608
CS-97004    1.906
CS-97005    3.448
            ...
CS-97567    3.798
CS-97568    3.772
CS-97569    3.470
CS-97570    2.193
CS-97571    1.753
Name: CGPA, Length: 571, dtype: float64

In [17]:
#SCALING TO REMOVE BIASNESS - STANDARD SCALING
from sklearn.preprocessing import StandardScaler
st=StandardScaler()
x1=st.fit_transform(x1)
x1

array([[ 0.40040198,  1.77089951,  1.72226058, ...,  1.74051347,
        -0.34612103, -0.45017773],
       [-1.24205154,  1.4115592 ,  2.39744822, ...,  0.90041779,
         0.72798282, -0.02104337],
       [-1.24205154, -0.74448263, -0.97848996, ..., -1.61986925,
        -0.70415565, -1.30844646],
       ...,
       [-0.25657943, -1.82250355, -0.30330233, ...,  0.06032211,
        -0.70415565, -0.45017773],
       [-1.24205154, -0.38514232,  2.0598544 , ..., -0.35972573,
         0.3699482 ,  1.26635973],
       [ 0.72889268,  1.4115592 ,  2.0598544 , ...,  0.06032211,
         1.80208667,  2.12462846]])

In [18]:
x1=pd.DataFrame(data=x1)
x1

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
0,0.400402,1.770900,1.722261,0.549869,1.374222,2.657832,1.790004,1.333963,0.419492,1.024565,...,0.663660,1.169315,1.155824,1.533685,0.958939,-0.399094,-0.960095,1.740513,-0.346121,-0.450178
1,-1.242052,1.411559,2.397448,1.488043,0.369509,1.173242,1.790004,-1.307365,2.302589,1.342687,...,1.715324,1.764660,1.521056,0.862110,1.325686,-0.399094,1.042149,0.900418,0.727983,-0.021043
2,-1.242052,-0.744483,-0.978490,0.237145,0.034605,-1.053643,0.322008,0.013299,-0.710366,-0.884168,...,-0.738559,-0.319046,-0.670339,-1.152616,0.225444,-1.210063,-0.960095,-1.619869,-0.704156,-1.308446
3,1.714365,0.692879,2.397448,1.488043,1.709126,-0.311348,2.157003,1.333963,1.925970,0.706443,...,1.364769,1.764660,0.425358,2.205260,0.958939,0.817361,0.241251,1.320466,1.086017,1.695494
4,-0.585070,-1.103823,-0.303302,-0.075580,-1.305012,-1.053643,-0.778989,0.013299,-1.463605,-0.884168,...,-0.738559,0.276298,-0.305107,0.190534,-0.141304,-0.399094,-0.960095,-0.779774,-0.704156,-1.308446
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,-0.256579,-1.822504,-0.978490,-0.701029,-0.970108,-1.053643,-0.778989,-0.647033,-1.086986,-0.247924,...,-0.037450,-0.616719,-1.035572,-1.152616,-1.975041,-1.210063,0.641700,0.060322,-0.346121,-1.308446
567,-0.913561,-1.822504,-0.978490,-1.326478,-1.305012,-1.053643,-1.512987,-0.647033,-1.463605,-1.520412,...,-0.738559,-0.021374,-0.305107,-1.152616,-1.975041,-0.399094,0.241251,-0.779774,0.727983,-0.450178
568,-0.256579,-1.822504,-0.303302,-0.075580,-1.305012,-1.053643,-1.512987,-1.307365,-1.463605,-0.566046,...,-0.037450,-0.616719,-0.670339,-1.152616,-0.508051,-1.210063,1.442597,0.060322,-0.704156,-0.450178
569,-1.242052,-0.385142,2.059854,-1.326478,1.709126,2.657832,0.322008,1.333963,0.419492,1.024565,...,-0.037450,1.466987,-0.670339,-0.145253,0.958939,2.439300,1.442597,-0.359726,0.369948,1.266360
570,0.728893,1.411559,2.059854,0.549869,0.704413,2.657832,-0.411990,1.003797,0.796111,1.660810,...,2.065879,0.871643,0.425358,0.526322,1.325686,3.250269,2.243495,0.060322,1.802087,2.124628

In [19]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif = pd.DataFrame()
vif["VIF Factor"] = [variance_inflation_factor(x1.values, i) for i in range(x1.shape[1])]
vif["features"] = x1.columns
vif

    VIF Factor  features
0     2.827608         0
1     1.771294         1
2     2.514966         2
3     2.293035         3
4     2.638921         4
5     2.366597         5
6     1.927701         6
7     1.968027         7
8     2.190768         8
9     2.294552         9
10    2.350875        10
11    1.633210        11
12    2.277248        12
13    2.254361        13
14    2.798314        14
15    3.084264        15
16    2.640904        16
17    2.612616        17
18    2.688396        18
19    2.435192        19
20    2.770283        20
21    3.022915        21
22    2.052599        22
23    2.113301        23
24    2.498852        24
25    3.095874        25
26    2.741509        26
27    2.889101        27
28    2.027056        28
29    3.275353        29
30    2.355677        30
31    3.471549        31
32    3.239651        32
33    3.161398        33
34    2.504472        34
35    2.813594        35
36    2.166488        36
37    2.294821        37
38    2.553670        38
39    2.559626        39
40    2.372103        40

From the above data frame it is clear that the dataset is free from multicolinearity problem

MODELLING

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [21]:
x1_train,x1_test,y1_train,y1_test=train_test_split(x1,y1,test_size=0.30,random_state=42)

In [22]:
#LINEAR REGRESSION
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
m1=LinearRegression()
m1.fit(x1_train,y1_train)
trainprediction1=m1.predict(x1_train)
print(r2_score(y1_train,trainprediction1))
testprediction1=m1.predict(x1_test)
print(r2_score(y1_test,testprediction1))
score1=cross_val_score(m1,x1,y1)
print(score1)
print(score1.mean())
print((r2_score(y1_test,testprediction1)-(score1.mean())))

0.9179670743496312
0.9531342955713245
[0.8927601  0.93427094 0.90082619 0.94061762 0.84878197]
0.9034513625626615
0.049682933008663

In [23]:
#ADA BOOST REGRESSION
from sklearn.ensemble import AdaBoostRegressor
m2=AdaBoostRegressor()
m2.fit(x1_train,y1_train)
trainprediction2=m2.predict(x1_train)
print(r2_score(y1_train,trainprediction2))
testprediction2=m2.predict(x1_test)
print(r2_score(y1_test,testprediction2))
score2=cross_val_score(m2,x1,y1)
print(score2)
print(score2.mean())
print((r2_score(y1_test,testprediction2)-(score2.mean())))

0.937614230249071
0.8922239660076114
[0.8573735  0.89619928 0.89083377 0.870605   0.78502481]
0.860007273389375
0.03221669261823645

In [24]:
#GRADIENT BOOST REGRESSION
from sklearn.ensemble import GradientBoostingRegressor
m3=AdaBoostRegressor()
m3.fit(x1_train,y1_train)
trainprediction3=m3.predict(x1_train)
print(r2_score(y1_train,trainprediction3))
testprediction3=m3.predict(x1_test)
print(r2_score(y1_test,testprediction3))
score3=cross_val_score(m3,x1,y1)
print(score3)
print(score3.mean())
print((r2_score(y1_test,testprediction3)-(score3.mean())))

0.9355030592052341
0.8929205271781101
[0.87665373 0.89433575 0.89309869 0.88660629 0.80669927]
0.87147874646695
0.021441780711160097

In [25]:
#RANDOM FOREST REGRESSION
from sklearn.ensemble import RandomForestRegressor
m4=RandomForestRegressor()
m4.fit(x1_train,y1_train)
trainprediction4=m4.predict(x1_train)
print(r2_score(y1_train,trainprediction4))
testprediction4=m4.predict(x1_test)
print(r2_score(y1_test,testprediction4))
score4=cross_val_score(m4,x1,y1)
print(score4)
print(score4.mean())
print((r2_score(y1_test,testprediction4)-(score4.mean())))

0.9863357881539533
0.9476649306442464
[0.91244042 0.92259724 0.94228267 0.91352103 0.84840475]
0.9078492214393064
0.03981570920494004

In [26]:
#DECISION TREE REGRESSION
from sklearn.tree import DecisionTreeRegressor
m5=DecisionTreeRegressor()
m5.fit(x1_train,y1_train)
trainprediction5=m5.predict(x1_train)
print(r2_score(y1_train,trainprediction5))
testprediction5=m5.predict(x1_test)
print(r2_score(y1_test,testprediction5))
score5=cross_val_score(m5,x1,y1)
print(score5)
print(score5.mean())
print((r2_score(y1_test,testprediction5)-(score5.mean())))

1.0
0.8570950599105787
[0.771532   0.77706935 0.90092824 0.75783148 0.74254633]
0.7899814806449525
0.06711357926562611

In [27]:
#SVR
from sklearn.svm import SVR
m6=SVR()
m6.fit(x1_train,y1_train)
trainprediction6=m6.predict(x1_train)
print(r2_score(y1_train,trainprediction6))
testprediction6=m6.predict(x1_test)
print(r2_score(y1_test,testprediction6))
score6=cross_val_score(m6,x1,y1)
print(score6)
print(score6.mean())
print((r2_score(y1_test,testprediction6)-(score6.mean())))

0.9694336764984327
0.9406661300927427
[0.89656309 0.92627299 0.90977131 0.9411797  0.85204761]
0.9051669400105776
0.035499190082165066

In [28]:
#KNN
from sklearn.neighbors import KNeighborsRegressor
m7=KNeighborsRegressor()
m7.fit(x1_train,y1_train)
trainprediction7=m7.predict(x1_train)
print(r2_score(y1_train,trainprediction7))
testprediction7=m7.predict(x1_test)
print(r2_score(y1_test,testprediction7))
score7=cross_val_score(m7,x1,y1)
print(score7)
print(score7.mean())
print((r2_score(y1_test,testprediction7)-(score7.mean())))

0.915783598329327
0.9563999030006821
[0.88957963 0.9359176  0.8654431  0.96068931 0.80762497]
0.891850920275352
0.06454898272533016

In [29]:
#Lasso
from sklearn.linear_model import Lasso
m8=Lasso()
m8.fit(x1_train,y1_train)
trainprediction8=m8.predict(x1_train)
print(r2_score(y1_train,trainprediction8))
testprediction8=m8.predict(x1_test)
print(r2_score(y1_test,testprediction8))
score8=cross_val_score(m8,x1,y1)
print(score8)
print(score8.mean())
print((r2_score(y1_test,testprediction8)-(score8.mean())))

0.0
-0.03739769771335144
[-0.00643799 -0.0037979  -0.00364638 -0.00242138 -0.02411396]
-0.008083520623131602
-0.02931417709021984

In [30]:
#Ridge
from sklearn.linear_model import Ridge
m9=Ridge()
m9.fit(x1_train,y1_train)
trainprediction9=m9.predict(x1_train)
print(r2_score(y1_train,trainprediction9))
testprediction9=m9.predict(x1_test)
print(r2_score(y1_test,testprediction9))
score9=cross_val_score(m9,x1,y1)
print(score9)
print(score9.mean())
print((r2_score(y1_test,testprediction9)-(score9.mean())))

0.9179661542208563
0.9534563216690646
[0.89292168 0.93429658 0.90102969 0.94099039 0.84890717]
0.9036291005426633
0.049827221126401255

In [31]:
#ExtraTreeRegressor
from sklearn.ensemble import ExtraTreesRegressor
m10=ExtraTreesRegressor()
m10.fit(x1_train,y1_train)
trainprediction10=m10.predict(x1_train)
print(r2_score(y1_train,trainprediction10))
testprediction10=m10.predict(x1_test)
print(r2_score(y1_test,testprediction10))
score10=cross_val_score(m10,x1,y1)
print(score10)
print(score10.mean())
print((r2_score(y1_test,testprediction10)-(score10.mean())))

1.0
0.9515955391500724
[0.91710906 0.95067197 0.94707476 0.95160015 0.87887252]
0.929065692649481
0.02252984650059142

Hence Extra Tree Regressor is selected as the best model based on the cv score

In [32]:
from sklearn.model_selection import GridSearchCV
parameters={'criterion':['squared_error','absolute_error','friedman_mse','poisson'],'n_jobs':[-1,1],'max_features':['sqrt','log2'],'bootstrap':[True,False],'oob_score':[True,False]}
gridsearchcv=GridSearchCV(ExtraTreesRegressor(),parameters,cv=5)
gridsearchcv.fit(x1_train,y1_train)

GridSearchCV(cv=5, estimator=ExtraTreesRegressor(),
             param_grid={'bootstrap': [True, False],
                         'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse', 'poisson'],
                         'max_features': ['sqrt', 'log2'], 'n_jobs': [-1, 1],
                         'oob_score': [True, False]})

In [33]:
gridsearchcv.best_params_

{'bootstrap': False,
 'criterion': 'friedman_mse',
 'max_features': 'log2',
 'n_jobs': 1,
 'oob_score': False}

In [34]:
best_model=ExtraTreesRegressor(criterion='friedman_mse',max_features='log2',bootstrap=False,n_jobs=-1,oob_score=False)
best_model.fit(x1_train,y1_train)
prediction=best_model.predict(x1_test)
print(r2_score(y1_test,prediction))

0.9557838632232114

In [37]:
#SAVING THE BEST MODEL
import joblib
joblib.dump(best_model,"CGPA.pkl")

['CGPA.pkl']

In [39]:
reload=joblib.load('CGPA.pkl')
reload.predict(x1_test)

array([2.16388, 3.41564, 2.79405, 2.29544, 3.74149, 3.36874, 2.67308,
       2.28792, 2.26135, 2.97256, 3.39338, 2.93898, 3.66897, 2.51611,
       3.81832, 2.66868, 2.26724, 3.55252, 2.02442, 2.29134, 2.31218,
       3.74207, 2.45031, 2.51605, 2.81335, 3.26559, 3.19439, 2.61964,
       3.28272, 3.36733, 2.58229, 2.78625, 3.41461, 3.22038, 3.65207,
       2.95088, 2.63232, 3.81581, 2.78114, 2.10104, 3.66416, 3.36397,
       3.66329, 3.67266, 3.22296, 2.33935, 2.66296, 3.21638, 3.20979,
       3.72855, 3.06269, 3.472  , 3.26529, 3.57059, 3.28176, 3.07898,
       3.76985, 3.66481, 3.64122, 2.66351, 3.58534, 3.5552 , 3.75685,
       3.36858, 3.34186, 3.02661, 3.3745 , 3.26936, 2.89388, 2.33473,
       3.61874, 3.27588, 2.62225, 3.68883, 3.82898, 3.33683, 3.25124,
       2.20704, 3.79988, 2.74963, 2.42351, 2.90636, 1.88307, 2.67817,
       3.74899, 3.67843, 3.19093, 3.02898, 2.75792, 2.17069, 2.97438,
       3.01149, 2.65161, 2.785  , 2.11357, 3.64626, 3.70635, 3.07081,
       2.92567, 2.91082, 3.50844, 3.28682, 3.25212, 2.50806, 2.98149,
       3.51891, 2.52965, 2.65164, 2.61095, 2.71933, 2.70018, 3.33025,
       3.64947, 3.39325, 2.65939, 3.66384, 3.75217, 3.03236, 2.22276,
       2.75926, 2.66802, 2.04904, 2.87033, 2.82971, 2.88188, 2.7852 ,
       2.10224, 3.08928, 3.48867, 3.17264, 2.33471, 2.52615, 3.54667,
       3.04134, 1.90619, 2.91559, 2.53454, 3.38098, 2.23238, 2.53905,
       3.00046, 3.48972, 3.68591, 3.17072, 3.88777, 3.01431, 2.67239,
       3.125  , 3.06575, 3.56367, 3.76905, 2.99809, 2.73146, 2.00345,
       3.72398, 3.06319, 3.18664, 2.72422, 2.13697, 3.21898, 3.07495,
       3.6054 , 2.70091, 3.29815, 2.17922, 2.24859, 2.86799, 3.52025,
       1.98475, 3.376  , 3.86314, 2.65893])

In [41]:
import pickle
filename='CGPA.pkl'
pickle.dump(best_model,open(filename,'wb'))
loaded_model=pickle.load(open('CGPA.pkl','rb'))
result=loaded_model.score(x1_test,y1_test)
print(result)

0.9557838632232114

In [44]:
ds12=pd.DataFrame([loaded_model.predict(x1_test)[:],y1_test[:]])
ds12

,0,1,2,3,4,5,6,7,8,9,...,162,163,164,165,166,167,168,169,170,171
0,2.16388,3.41564,2.79405,2.29544,3.74149,3.36874,2.67308,2.28792,2.26135,2.97256,...,2.70091,3.29815,2.17922,2.24859,2.86799,3.52025,1.98475,3.376,3.86314,2.65893
1,1.99200,3.49000,2.82300,2.28800,3.81600,3.47600,2.63400,2.29400,2.17100,3.06000,...,2.77900,3.40800,1.80600,2.08400,2.89100,3.57800,1.76400,3.369,3.91900,2.61200